//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspStudentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollments
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateEnrollment { get; set; }
        public int ClasseId { get; set; }
        public string studentId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Classes Classes { get; set; }
    }
}
